# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90668d54e0aa7bded1e802adda95eab2a2958d07c8e0949d6de12f1d804b1dd35226aaf6f92f1ed5fee3907de49cfc1fc3e3072b45c8e0438d8110b0ca6a235d

test:
  secret_key_base: 8bbfc09680dad63f1ecc4b1d093b1c6c0419477e4186d76f756f6d85af0b5db9b566f9e290869b71eae25a10db0c13bcab1533888541d5c76bbe3be2ca50b751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
